#!/usr/bin/env bash
# Tranfers a file to a server using SSH
if [ $# -ge 3 ]
then
    if [ $# -eq 3 ]
    then
        # No private key provided
        scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
    else
        # Private key provided
        scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
    fi
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
