#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.

if ! ( haproxy -v &>/dev/null ); then
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.6 -y
sudo apt update -y &&\
        sudo apt-get install haproxy=2.6.\* -y
fi

config=\
"
defaults
    mode http
    timeout client 30s
    timeout connect 15s
    timeout server 15s
    timeout http-request 15s

frontend web_frontend
    bind *:80
    default_backend web_backend

backend web_backend
    balance roundrobin
    server 4888-web-01 34.239.160.19:80 check
    server 4888-web-02 34.231.243.196:80 check
"

sudo cp /etc/haproxy/haproxy.cfg haproxy.cfg.backup

echo "$config" | sudo tee /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee /etc/default/haproxy

if [ "$(pgrep -c haproxy)" -eq 0 ]; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi

