#!/usr/bin/env bash
# Configures Nginx to be running, and listening on port 80 of all the server’s active IPv4 IPs

sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
