#!/usr/bin/env bash
# This script prints bad luck, good luck or Best School in a loop
i=1
while [ $i -le 10 ] 
do
  if [ $i -eq 8 ]
  then
    printf "good luck\n"
  elif [ $i -eq 4 ]
  then
    printf "bad luck\n"
  else
    printf "Best School\n"
  fi
  i=$(( i + 1 ))
done
