#!/usr/bin/env bash
# This script prints bad luck, good luck or Best School in a loop
i=1
while [ $i -le 20 ] 
do
  printf "%d\n" "$i"
  case $i in
    5)
      printf "bad luck from China\n"
      ;;
    10)
      printf "bad luck from Japan\n"
      ;;
    17)
      printf "bad luck from Italy\n"
      ;;
  esac
  i=$(( i + 1 ))
done
