#!/usr/bin/env bash
#This script prints Best School 10 times
i=0
while [ $i -le 12 ] 
do
  printf "Hour: %d\n" "$i"
  j=1
  while [ $j -lt 60 ]
  do
    echo "$j"
    j=$(( j + 1 ))
  done
  i=$(( i + 1 ))
done
